### ISSUE TITLE
Create skeleton of the application using SlicerCustomAppTemplate

### ISSUE THREAD

**Issue by jcfr** [BICCN/cell-locator#1]
See https://github.com/KitwareMedical/SlicerCustomAppTemplate

* [x] Update SlicerCustomAppTemplate to use latest version of Slicer
* [x] Generate skeleton using cookiecutter (Project name: CellLocator, Description: Manually align specimens to annotated 3D spaces)

**Comment by vovythevov** [comment]
See commit d3290e7e142e2c327e242d68bfaa7340e1ea467c
