### ISSUE TITLE
Display the CCF average template colored by annotations (not just the annotations)

### ISSUE THREAD

**Issue by dyf** [BICCN/cell-locator#10]
Example from connectivity.brain-map.org here:

![image](https://user-images.githubusercontent.com/1854389/42642953-d37e2ad0-85ac-11e8-9e39-24374992cd4c.png)

The `average_template_<resolution>.nrrd` image should be the background image with the annotation/segment colors (`annotation_<resolution>.nrrd`) in the foreground.

**Comment by jcfr** [comment]
This is now fixed. Here is the screenshot of the viewer in Cell-locator:

![image](https://user-images.githubusercontent.com/219043/45193575-b167d300-b21c-11e8-98b8-cd3ac70753f0.png)
