### ISSUE TITLE
System dialog can load directory from network path

### ISSUE THREAD

**Issue by wbwakeman** [BICCN/cell-locator#103]
**What's the problem this feature will solve?**
Load annotation.json file from network path.

**Describe the solution you'd like**
Ability to paste in a network location in order to select an annotation.json file at that location.
e.g.
\\allen\programs\celltypes\workgroups\tppd\Tissue_Processing\Cell_Prep\Cell_Locator_Dissections\20191001_487984.003

I suppose if I were on a Linux or MacOS, I would also want to use paths like this:
/allen/programs/celltypes/workgroups/tppd/Tissue_Processing/Cell_Prep/Cell_Locator_Dissections/20191001_487984.003

I want to view the annotation that another user has made and saved to a network drive.  Currently, I need to mount that network location on my Windows computer, and then select each folder until I get to the one containing the json file.

**Alternative Solutions**
none

**Additional context**
If I load a file from a location, and then I click 'load' to load another file, it would be great if the file select widget opened at same the location where I loaded the previous file, rather than from my Documents folder again.

**Comment by jcfr** [comment]
> If I load a file from a location, and then I click 'load' to load another file, it would be great if the file select widget opened at same the location where I loaded the previous file, rather than from my Documents folder again.

This is tracked by #101 and fixed in ab03e56a28746

**Comment by wbwakeman** [comment]
Looks like I can do this now.  Suggest to close this issue.

**Comment by jcfr** [comment]
Closing. This was likely fixed by the Qt version updates.
