### ISSUE TITLE
Use LastAnnotationDirectory for re-loading annotation

### ISSUE THREAD

**Issue by jcfr** [BICCN/cell-locator#105]
**What's the problem this feature will solve?**
Directory last use for loading should be used for loading another annotation as well.

**Describe the solution you'd like**
Re-use the `LastAnnotationDirectory` settings to initialize the load annotation dialog

**Additional context**
See #85 and https://github.com/BICCN/cell-locator/issues/103#issue-597576589

**Comment by wbwakeman** [comment]
This works great in the new 4/30/2020 release.  Thanks @jcfr
