### ISSUE TITLE
Convert output json files into volumetric mask in python

### ISSUE THREAD

**Issue by danielsf** [BICCN/cell-locator#107]
**What's the problem this feature will solve?**

We would like to be able to take regions drawn in the cell locator and convert them into volumetric masks aligned to the Allen Institute's CCF that can be overlaid atop the Allen Institute reference atlases. This will allow us to, for instance, count the number of voxels in the drawn region that occur in each of the annotated brain regions in the reference atlas.

**Describe the solution you'd like**

If you can provide documentation describing the schema of the json files output by the cell locator, we can add functionality to the AllenSDK that does the work of aligning the regions to the CCF and combining them with the reference atlas. If you would rather build the API yourself, we can provide more details*, but again: we are prepared to build the json-to-CCF API ourselves; we just need to understand the contents of the json files.

*this project is still in the R&D phase, so specifying the API may require some iteration

**Alternative Solutions**

**Additional context**

**Comment by jcfr** [comment]
> volumetric mask, count the number of voxels

Few questions and remarks:

1. Instead of updating the AllenSDK to understand a non standard json format, what about providing API to generate label maps (`.nrrd` file) (one for each region) ?

2. Considering we have a segment (aka label map) statistics module in Slicer (and by extension CellLocator), we could already get the number of voxels for a given  region. See https://slicer.readthedocs.io/en/latest/user_guide/module_segmentstatistics.html

**Comment by danielsf** [comment]
@jcfr The only part of the `json` files that I did not understand is what `SplineOrientation` meant. It appears that, regardless of the number of points in the spline, `SplineOrientation` always contains 16 elements. Can you let me know the mathematical definition of what this represents?

**Comment by jcfr** [comment]
This are the direction cosines defining the orientation of the plane on which the annotation is drawn.

**Comment by danielsf** [comment]
@jcfr
Can you post a link to the code that implements the interpolations for spline-based annotations? Thanks.

**Comment by danielsf** [comment]
I assume the spline is implemented using this class from VTK

https://gitlab.kitware.com/vtk/vtk/-/blob/master/Common/ComputationalGeometry/vtkKochanekSpline.cxx

?

**Comment by jcfr** [comment]
The widget used to represent the spline in 3D is [vtkSplineWidget2](https://github.com/Slicer/VTK/blob/fd1f5b46bde3762e78e9765eb84595cc2ebb3c71/Interaction/Widgets/vtkSplineWidget2.cxx) used in [vtkMRMLMarkupsSplinesDisplayableManager3D](https://github.com/BICCN/cell-locator/blob/604de038819daf91751ebb4a54f1cbfd7e06e0b9/Modules/Loadable/Splines/MRMLDM/vtkMRMLMarkupsSplinesDisplayableManager3D.cxx#L261) and [vtkMRMLMarkupsSplinesDisplayableManager2D](https://github.com/BICCN/cell-locator/blob/604de038819daf91751ebb4a54f1cbfd7e06e0b9/Modules/Loadable/Splines/MRMLDM/vtkMRMLMarkupsSplinesDisplayableManager2D.cxx#L265)

The representation used in the widget is the default one. See [vtkSplineWidget2::CreateDefaultRepresentation()](https://github.com/Slicer/VTK/blob/fd1f5b46bde3762e78e9765eb84595cc2ebb3c71/Interaction/Widgets/vtkSplineWidget2.cxx#L239) and [vtkSplineRepresentation](https://github.com/Slicer/VTK/blob/fd1f5b46bde3762e78e9765eb84595cc2ebb3c71/Interaction/Widgets/vtkSplineRepresentation.cxx)

Within the spine representation, spline interpolation is done using [vtkParametricSpline](https://github.com/Slicer/VTK/blob/fd1f5b46bde3762e78e9765eb84595cc2ebb3c71/Interaction/Widgets/vtkSplineRepresentation.cxx#L58-L86), which itself uses [vtkCardinalSpline](https://github.com/Slicer/VTK/blob/fd1f5b46bde3762e78e9765eb84595cc2ebb3c71/Common/ComputationalGeometry/vtkParametricSpline.cxx#L32-L34) and [vtkCardinalSpline::Evaluate](https://github.com/Slicer/VTK/blob/fd1f5b46bde3762e78e9765eb84595cc2ebb3c71/Common/ComputationalGeometry/vtkCardinalSpline.cxx#L29-L77)

Finally, the generated contour is used to create the model in the function [vtkSlicerSplinesLogic::CreateModelFromContou](https://github.com/BICCN/cell-locator/blob/7d7f2afa7821341a91da9b8bd48c8c95a61123dc/Modules/Loadable/Splines/Logic/vtkSlicerSplinesLogic.cxx#L151-L224)

**Comment by jcfr** [comment]
After we update the version of Slicer will be using an improved implementation of the spine widget allowing us to choose different interpolation function . In this case, the Kochanek spline will be available.

Here is a screenshot from the option is the latest Slicer:

![image](https://user-images.githubusercontent.com/219043/83295687-62668c00-a1bd-11ea-80c2-9e3fc11f66b0.png)

**Comment by jcfr** [comment]
Note that you should be able to `pip install vtk` to make use of corresponding functions.

Also worth noting that in few days, we will have updated VTK wheels for v9.0.0 available for all platforms (if you are curious see [here](https://gitlab.kitware.com/vtk/vtk/-/issues/17695#note_767184))

**Comment by jcfr** [comment]
Clo
