### ISSUE TITLE
Message indicating Save because of "mofication", when there's been no modification

### ISSUE THREAD

**Issue by joshusama** [BICCN/cell-locator#111]
**Environment**

Windows 10

**Description**

When closing a file that hasn't at all been modified, there's a prompt to save that suggest that it has been changed.  

**Expected behavior**

If a file hasn't been changed/modified, there should be no message indication so.  It's confusing and creates doubt about what you think is going on or file you have opened or are going to close.

**How to Reproduce**

1. Load a file
2. Immediately create +NEW without modifying the opened file
3. It will give the message asking you to save because it's been modified

<img width="1511" alt="Message" src="https://user-images.githubusercontent.com/62865127/81714136-986ce780-942b-11ea-86c5-5f1bd4625aac.png">

**Comment by wbwakeman** [comment]
Also, clicking "No" on that dialog still forces user to save a file.
