### ISSUE TITLE
Spline polygons do not save, but also do not disappear in a session involing multiple files

### ISSUE THREAD

**Issue by joshusama** [BICCN/cell-locator#112]
**Environment**

* OS:

Windows 10, Cell Locator 4-30 build

**Description**

When a spline is drawn or even begun to be drawn and switched over to polyline, the resulting region that appears normal will not save.  There's no indicator of this until later when the file is reopened and it's empty.  Furthermore, when a spline has been created and saved, when a +NEW file is created, it carries over into that new file.  Now when you draw a polygon, you'll see that "ghost" line in addition to your new one.  It also appears that when you save that new file, depending if it was a polyline or spline, you might have a file that ends up blank, with two polygons or just the last one.  Still investigating.

**Expected behavior**
When drawing a polygon, whether spline or polyline, it should save and not ghost into subsequent files.

**How to Reproduce**

1. Start the application
2. Draw a spline polygon
3. Save
4. +NEW file 
5. The previous file's polygon persists
6. Draw polygon in this new file and save (will appear as if you've save a file with two polygons)
7. Close program entirely
8. Relaunch program
9. Load first file, observe that it's likely empty
10. Load second file, observe that it may be empty, have the second polygon or both polygons

![image](https://user-images.githubusercontent.com/62865127/81715548-357c5000-942d-11ea-9dad-053f72801294.png)

**Comment by jcfr** [comment]
Following re-factoring and improvement associated with Slicer updates, this issue is not reproducible. Closing.
