### ISSUE TITLE
Polygon in loaded file may not show up in drawing window

### ISSUE THREAD

**Issue by joshusama** [BICCN/cell-locator#113]
**Environment**

* OS:

Windows 10, build 04/30

**Description**
Sometimes a polygon will disappear from the drawing window even though there's evidence of its presence in right window.  Carefully scrolling through every plate in its range does not make it appear.

**Expected behavior**
Polygon should appear in drawing window for manipulation

**How to Reproduce**
 
May be spurious as it happens only with some files.  The screencap here shows that it's on the same plane as the right window, but not showing up on the left.  Again, even when scrolling plate-by-plate, it never shows up.

![image](https://user-images.githubusercontent.com/62865127/81716083-d1a65700-942d-11ea-98b1-5a593697cfeb.png)

**Comment by jcfr** [comment]
Following the integration of #131 , the infrastructure to manage annotations has been completed revamped.

I am closing this for now and suggest a new issue is created once more testing is dong with the upcoming release.
