### ISSUE TITLE
Decide on logo and splash screen text

### ISSUE THREAD

**Issue by mgrauer** [BICCN/cell-locator#13]
Is there an existing logo for the Cell Locator app or should @jtomeck create one?

What should the splash screen text say?

**Comment by mgrauer** [comment]
For the time being, we will develop the UI to be aligned with the overall Allen style guide provided to us.

**Comment by jcfr** [comment]
![biccn-logo-blue-cell-locator-300ppi](https://user-images.githubusercontent.com/219043/52752801-2e645900-2fc2-11e9-84a4-57e2103e1044.png)
![biccn-logo-blue-cell-locator-72ppi](https://user-images.githubusercontent.com/219043/52752802-2e645900-2fc2-11e9-84eb-c4717cb04fd4.png)

**Comment by jcfr** [comment]
![desktopicon](https://user-images.githubusercontent.com/219043/52821137-ea358f00-307b-11e9-83fe-5bdbfa0e7a76.png)

![desktopicon](https://user-images.githubusercontent.com/219043/52821146-ef92d980-307b-11e9-9544-82db5a05525e.png)

**Comment by mgrauer** [comment]
Nice!

**Comment by jcfr** [comment]
![image](https://user-images.githubusercontent.com/219043/52825061-4521b300-3089-11e9-80dc-9b39b938aa5b.png)

**Comment by jtomeck** [comment]
![biccn_cell_locator_logo](https://user-images.githubusercontent.com/1560779/52960171-2f044300-3366-11e9-80be-2b9fc1e069d0.png)

Here's the cleaned up logo. I also created it in SVG form so we have a vector version of it in the future (see zip below).

[Logo.zip](https://github.com/BICCN/cell-locator/files/2876248/Logo.zip)

**Comment by jtomeck** [comment]
![2d69jj5jfi](https://user-images.githubusercontent.com/1560779/52960764-77703080-3367-11e9-9b20-474e5e29a0a3.gif)

Comparison gif
