### ISSUE TITLE
Last directories for save/load are not remembered. (Slicer 2020)

### ISSUE THREAD

**Issue by allemangD** [BICCN/cell-locator#137]
**Environment**

* OS: Ubuntu 20.04
* Revision: PR https://github.com/BICCN/cell-locator/pull/131

**Description**

The last directory used for saving is not remembered by the save dialog, nor the last directory for loading by the load dialog.

**Expected behavior**

After saving an annotation to some directory, subsequent Save As dialogs should initially be at that directory.

**How to Reproduce**

Last-used save directory:

1. Start the application
2. Save the annotation (via Save or Save As)
3. Click "Save As"

Last-used load directory:

1. Start the application
2. Load an annotation
2. Click "Load"

**Comment by jcfr** [comment]
The root cause of this is likely the crash on exit.
