### ISSUE TITLE
Slice Offset in certain scenarios differs from expected value. (Slicer 2020)

### ISSUE THREAD

**Issue by allemangD** [BICCN/cell-locator#139]
**Environment**

* OS: Ubuntu 20.04
* Revision: https://github.com/BICCN/cell-locator/pull/131

**Description**

The default slice offset is -6575, but according to the [qa checklist](https://github.com/BICCN/cell-locator/blob/master/.github/ISSUE_TEMPLATE/qa-checklist.md) is expected to be 6600.

Similarly, performing the Roll/Pitch/Yaw test in the qa checklist produces a slice offset of -9472, but is expected to be 9478.

The numbers are close, except for their sign. I have a hunch this is due to the changed coordinate system, and may be related to issue https://github.com/BICCN/cell-locator/issues/101.

**Comment by jcfr** [comment]
>  I have a hunch this is due to the changed coordinate system, and may be related to issue #101.

Agreed with your assessment.

**Comment by allemangD** [comment]
This is just due to the coordinate system change.

For example, with the Coronal slice offset: the anterior extent offset is -13175um, and the initial offset is -6575um; then the difference from the extent is then +6600um. So when the coordinates were negated, there would have been a +6600um. 

The other offset differences are:

- Axial: 7975 -  3975 = 4000
- Sagittal: 11374 - 1 - 5699 = 5674   (because the left extent is +1um, not 0.)

Since the relative positions are still the expected values, I'll update the qa checklist with the positions and a note mentioning this comment. If we do want to maintain the old values (and all-positive coordinates), that should be done as part of the work for https://github.com/BICCN/cell-locator/issues/196 by correcting the coordinate system and offsets used in the CCF atlas.
