### ISSUE TITLE
Saving through exit confirmation dialog still prevents application exit. (Slicer 2020)

### ISSUE THREAD

**Issue by allemangD** [BICCN/cell-locator#140]
**Environment**

* OS: Ubuntu 20.04
* Revision: PR https://github.com/BICCN/cell-locator/pull/131

**Description**

The confirmation dialog prevents exit even if file saving was successful.

**How to Reproduce**

1. Start the application
2. Edit the annotation
3. Click "X" to exit.
4. Choose "Save" in the dialog.
5. Select a location.

The file should have saved successfully, but the application still does not exit. Clicking "X" to exit will still open the dialog.

**Comment by wbwakeman** [comment]
Is #111 possibly related to this?
