### ISSUE TITLE
Update json  file to use "annotations" key instead of "markups" 

### ISSUE THREAD

**Issue by jcfr** [BICCN/cell-locator#151]
>Should we keep the terminology "markups / markup" or change it to "annotations / annotation" ?

I'm not too fussed either way.  "annotations / annotation" probably has broader appeal to scientific users.  Just let me know if you change it; I will have to make a matching change on my side.

w.r.t to multiple annotations, I guess this is enabled now?  #90 is just adding the GUI components so that users can manage more than one annotation? (e.g. "Now I am done modifying this annotation, and want to start adjusting the other one...")

_Originally posted by @wbwakeman in https://github.com/BICCN/cell-locator/issues/93#issuecomment-683171108_

**Comment by wbwakeman** [comment]
Suggest to close this one

**Comment by jcfr** [comment]
Closing. Updating the name from "markup[s]" to "annotation[s]" will not significantly improve usability.
