### ISSUE TITLE
Cell Locator 09-18-2020 cannot open files generated by previous versions

### ISSUE THREAD

**Issue by wbwakeman** [BICCN/cell-locator#158]
**Environment**

* OS:

Windows 10

**Description**
Trying to open one of the many .json files generated with previous versions of the Cell Locator in the new 09-18-2020 release.  They will not open.  The console shows messages like 'KeyError: markups' and "object has no attribute 'markup'"
File is copied here: https://gist.github.com/wbwakeman/34c0bf14023c295002c1375ab476e9d8

**Expected behavior**
The file should load, and Cell Locator should display the polygon

**How to Reproduce**
Open Cell Locator 0.1.0 2020-09-18 and load the json file identified in the gist

![20200918_cell_locator_cannot_open_previous_annotation_files](https://user-images.githubusercontent.com/1855315/94323025-1ea44900-ff49-11ea-8e95-b094026941bb.png)

**Comment by jcfr** [comment]
The annotations saved with the previous version of CellLocator are  not compatible with the current version.

Differences between format are document here: https://github.com/BICCN/cell-locator/blob/master/Documentation/AnnotationFileFormat.md

Would it help to have a python  script to convert from one version to an other ?

**Comment by wbwakeman** [comment]
Oh my.  I did not realize that would be the case.  We have generated thousands of annotation files already so yes, we do need some way to not lose all of that work.  A python script to convert them would be acceptable.

**Comment by jcfr** [comment]
No problem, next week I will address this in few phases:
* [ ] provide a scripts
* [ ] include version in annotation  file
* [ ] support automatic conversion in the application

**Comment by jcfr** [comment]
@wbwakeman  I am finalizing a script to convert from format [2019-01-26](https://github.com/BICCN/cell-locator/blob/master/Documentation/AnnotationFileFormat.md#2019-01-26) to format [2020-09-18](https://github.com/BICCN/cell-locator/blob/master/Documentation/AnnotationFileFormat.md#2020-09-18)
