### ISSUE TITLE
MNI annotation needs to be double sided

### ISSUE THREAD

**Issue by lydiang** [BICCN/cell-locator#164]
**Environment**

All environments

MNI annotation needs to be double sided to allow users/anatomists to efficiently navigate and find the right position to pin the sample

**Expected behavior**

MNI atlas is annotated with structures on both side

**How to Reproduce**

1. Start the application

![image](https://user-images.githubusercontent.com/8552673/112548131-fae78180-8d78-11eb-9ed9-6c2d27dba6f6.png)

**Comment by jcfr** [comment]
Here is the full atlas:

http://download.alleninstitute.org/informatics-archive/allen_human_reference_atlas_3d_2020/version_1/

File: annotation_full.nii.gz
