### ISSUE TITLE
Make switching between atlas an UI option instead of just command line

### ISSUE THREAD

**Issue by lydiang** [BICCN/cell-locator#165]
**Environment**

* OS:

Windows

**Description**

Currently, the only way to run Cell Locator is to start it up in the command line. Starting application from a command line with arguments is too difficult for our target users (research assistants, anatomists).

**Expected behavior**

Ability to switch to atlas in the UI or at the start of a session asking the user which atlas they would like to use

**How to Reproduce**

Volunteer to help someone to get started with using Cell Locator remotely, where the user never had the need to use the command prompt, shell scripting or to find the location of the executable.

**Comment by sjh26** [comment]
For this, we are going to go with popping up a dialog at launch to have the user select the atlas to use.
