### ISSUE TITLE
When drawing a second annotation, annotation type defaults to Spline eventhough the UI shows Polyline is selected

### ISSUE THREAD

**Issue by lydiang** [BICCN/cell-locator#179]
**Environment**

* OS: Windows 10
* Cell Locator: 0.1.0.2020-05-21

**Description**

Use Case:
I want to create many annotation of type "Polygon"
I draw my first "Polygon" and all is well

![image](https://user-images.githubusercontent.com/8552673/121581389-9f757900-c9e2-11eb-896f-01ffbeffde88.png)

I add a new curve and since seeing that  "Polygon" selected I start drawing

![image](https://user-images.githubusercontent.com/8552673/121581716-05fa9700-c9e3-11eb-8a32-a3746af8df88.png)

However, the application is actually in "Spline" mode

**Expected behavior**

The application behavior and the annotation type radio button indicator are consistent

**How to Reproduce**

(see description)

1. Start the application
2. Then run '...'
3. An error occurs.

**Comment by allemangD** [comment]
Linked to #188 by mistake - I've removed that so this should keep open even if #188 is merged.
