### ISSUE TITLE
Organize data

### ISSUE THREAD

**Issue by jcfr** [BICCN/cell-locator#2]
For now the CCF version is available on [Google drive](https://drive.google.com/drive/u/0/folders/1B7GkkMrsywRBEWtb-4PGeeqRGkid_lZK)

The idea would be organize them in https://github.com/BICCN/cell-locator where we would add a `CCF-VERSIONS.md` file.

Each time a new version of the CCF must be uploaded, a new entry like the following would be added to the file:

```
* YYYY-MM-DD: Short description
  * file1: sha256
  * file2: sha256
```

Then a tag named `ccf-YYYYMMDD` would be created and all files referenced in the new file entry would be uploaded as release assets.

**Comment by vovythevov** [comment]
Fixed with PR https://github.com/BICCN/cell-locator/pull/8
