### ISSUE TITLE
Example files for library function development

### ISSUE THREAD

**Issue by lydiang** [BICCN/cell-locator#212]
Per discussion with DavidA

I have put into the google drive, example annotation for three human brains
https://drive.google.com/drive/folders/1eDD2OftlZJ7glRf8OeWFV1gf2GqVd4CI?usp=sharing

I would like to be able to get a 3D mask file for each annotation in each json file.

**Comment by jcfr** [comment]
Closing. The cli for exporting annotation on PyPI[^1] and is documented here[^2] alongside cell-locator.

[^1]: https://pypi.org/project/cell-locator-cli/
[^2]: https://cell-locator.readthedocs.io/en/latest/command-line-tools.html
