### ISSUE TITLE
Documentation published on readthedocs is not current

### ISSUE THREAD

**Issue by jcfr** [BICCN/cell-locator#219]
**Description**

Documentation published at https://cell-locator.readthedocs.io/ is not automatically updated after pushing or integrating changes to the `master` branch.

After browsing to https://readthedocs.org/projects/cell-locator/ the following is reported:

![image](https://user-images.githubusercontent.com/219043/182201304-161d7c48-5cdc-4f0f-b696-fcd072357ab0.png)

Clicking on the [GitHub incoming webhook ](https://readthedocs.org/dashboard/cell-locator/integrations/208044/) link seems to correctly indicate that the payloads are received ....

![image](https://user-images.githubusercontent.com/219043/182201619-3a3224df-ee60-45b1-b0e5-5f26855b187d.png)

... that said the build are not started automatically

![image](https://user-images.githubusercontent.com/219043/182201957-b4d47c7e-a20a-4cd0-911f-818810c8008f.png)

Attempting to address this by clicking on **Resync webhook** leads to the following:

![image](https://user-images.githubusercontent.com/219043/182201753-1d48c989-cd2a-4930-8c17-894420ad0d3b.png)

**Expected behavior**

Automatic rebuild of the documentation.

**How to Reproduce**

Integrate a pull request and/or directly push changes to the `master` branch.

**Comment by jcfr** [comment]
@lydiang Assuming you have admin access to [BICCN](https://github.com/BICCN) GitHub organization, could you help with re-syncing the readthedocs webhook ? 

cc: @allemangD

**Comment by allemangD** [comment]
Discovered the issue is because rtd pulls the `latest` tag which had been set to 40e28bf0c422ac1a23896dad0440ea345f5c3cfb with no automation to update it.

I've updated that tag to the current `master` - see https://github.com/BICCN/cell-locator/commits/latest - but we should look into having rtd pull some a more appropriate branch, or set up automation to update `latest` after releases.

**Comment by jcfr** [comment]
> I've updated that tag to the current `master`

Thanks, inspecting the settings confirms this:

![image](https://user-images.githubusercontent.com/219043/204858361-a3448ebb-67cf-4487-b2c9-6cbea98ed0d4.png)

> we should look into having rtd pull a more appropriate branch, or set up automation to

Ditto. Since we already a webhook in place, build should happen automatically. I will confirm this by pushing (and then reverting) a commit to `master`. 

![image](https://user-images.githubusercontent.com/219043/204858841-42cae0da-b5ed-44a8-ac45-bc3ffadab4d8.png)

**Comment by jcfr** [comment]
After pushing to `master`:

| GitHub hook delivery | Readthedocs received payload 
|--|--|
| ![image](https://user-images.githubusercontent.com/219043/204930509-b8808038-74d9-4926-a114-b08d33922c10.png) | ![image](https://user-images.githubusercontent.com/219043/204930453-2b372a8c-fb36-4622-9ec8-b484ef287054.png) |

**Comment by jcfr** [comment]
Even after modifying a documentation file, the build is not triggered.

For sake of comparison:

| `Slicer` | `Cell Locator` |
|--|--|
|  ![image](https://user-images.githubusercontent.com/219043/204931651-1ec5d383-ba63-48f9-99bb-89ef0be8d9d9.png) |  ![image](https://user-images.githubusercontent.com/219043/204931574-f520c3d9-adf3-4dd5-8bc3-0fb4d92f7e1e.png) |

**Comment by jcfr** [comment]
Solution:
1. Make sure the default version in Advanced Settings is **not** "latest"
2. Deactivate `latest` in the versions list
3. Activate `master`
4. Go back to Advanced Settings and set `default version` as `master`, and default branch as `latest`

| Versions | Advanced Settings |
|--|--|
| ![image](https://user-images.githubusercontent.com/219043/204936089-33dbee64-5d63-48b4-bfb9-7b5905ef27f2.png) | ![image](https://user-images.githubusercontent.com/219043/204936130-48592e72-109c-44e8-8d20-4c1aac8ceb13.png) |

For comparison, here it the `Advanced Settings` before and after:

| Before | After |
|--|--|
| ![image](https://user-images.githubusercontent.com/219043/204936297-9b43b2e2-b5a3-4f50-b7f5-c3c0527662ec.png) | ![image](https://user-images.githubusercontent.com/219043/204936130-48592e72-109c-44e8-8d20-4c1aac8ceb13.png)  |

**Comment by jcfr** [comment]
It turns out that the following sequence worked:
1. Go to Advanced Settings, select something different from "Default version" (`latest`) and "Default branch" (`master`)
2. Go back to "Versions", and deactivate all version except the one selected in prevous step, then re-activate "latest"
3. Go back to Advanced Settings, select "Default version" (`latest`) and "Default branch" (`master`)

![image](https://user-images.githubusercontent.com/219043/204937452-6e410f6a-59b7-46df-82be-ecca39d766c1.png)

**Comment by jcfr** [comment]
@lydiang  I just sent a request for adding the Read the Docs [OAuth App](https://github.com/settings/applications) to the BICCN organization. When you have a chance, could you accept it ?


| https://github.com/settings/connections/applications/fae83c942bc1d89609e2 |
|--|
| ![image](https://user-images.githubusercontent.com/219043/204980115-43e8f366-ea30-4f4f-bbfc-136247857bbe.png) |

**Comment by lydiang** [comment]
approval done
________________________________

**Comment by jcfr** [comment]
Thanks @lydiang ,the  webhook has now been added/re-synced.

![image](https://user-images.githubusercontent.com/219043/205121054-db65c80b-c035-4de0-9a47-3962b0b97fd6.png)

![image](https://user-images.githubusercontent.com/219043/205121768-853ff22e-36d9-424d-8775-0b7c16535738.png)

Support for building preview of the documentation in pull-request also enabled :rocket: 

![image](https://user-images.githubusercontent.com/219043/205188485-120e3aea-0f88-4df8-80e5-b307c89ba56a.png)

**Comment by jcfr** [comment]
@allemangD  I just realized that we have a tag named `latest` and this is likely what is confusing the system.

![image](https://user-images.githubusercontent.com/219043/205189585-7153f32f-02a5-48fd-89e2-fbe9f16b9283.png), I will deleted the tag.

**Comment by jcfr** [comment]
After deleting the tag, readthedocs now show `main`:

![image](https://user-images.githubusercontent.com/219043/205189956-38558b70-20a6-44cb-853d-3443e5f862e3.png)
