### ISSUE TITLE
Saving view parameters along side annotation

### ISSUE THREAD

**Issue by jcfr** [BICCN/cell-locator#22]
Goal: Loading an existing annotation should bring up the same "viewer settings". These includes field of view/camera settings and slice index.

* the annotation will be in its own format

* we should also store the version of the atlas, template, cell-location application in the same file

@vovythevov 
* [ ] Could you investigate if there are standard for storing fiducials, custom attributes, software version, "acquisition/processing" settings etc ... may be a post on the Slicer discourse describing what we are trying to do from a high level. I think Andrey has spend a fair amount time working with standard file format.
* If there is an easy approach allowing to leverage some standard, I then suggest we use it. If not, we will role our own "format"

**Comment by vovythevov** [comment]
We also need to also save the generated model from the spline.

**Comment by jcfr** [comment]
> save the generated model from the spline.
Check with David which format. STL ? VTK ?

**Comment by dyf** [comment]
I don't think we *need* to save the annotations as 3D geometry or volumes from within the application (although it would be nice).  At minimum, we *do* need documentation for the correct way to do so.  For example:

```python
def generate_annotation_volume(spline, thickness, extent, spacing): 
    # fill this in
def generate_annotation_geometry(spline, thickness, extent, spacing): 
    # fill this in
```

**Comment by dyf** [comment]
Oh but if you want me to pick a format -- I like binary PLYs.

**Comment by vovythevov** [comment]
As for the ```generate_annotation_geometry```, the method is implemented in the [```vtkSplinesLogic::CreateModelFromContour()```](https://github.com/BICCN/cell-locator/blob/master/Modules/Loadable/Splines/Logic/vtkSlicerSplinesLogic.h#L59) method so it may be access from python easily.
