### ISSUE TITLE
Polyline annotation should be represented in 3D using a polydata with adjustable thickness

### ISSUE THREAD

**Issue by jcfr** [BICCN/cell-locator#26]
* color should be hardcoded
* seeing the existing the spline point is not a problem
* thickness should be a parameter that can be set externally (ideally by updating a node property)
* visibility (and opacity?) of the polydata should be configurable  (ideally by updating a node property)

**Comment by vovythevov** [comment]
Fixed as of: 204ff26e8329d06a567516303f0468ee8849ac74

Note: Minor issues like the opacity in the GUI will be spun off in other issues.
