### ISSUE TITLE
Associated polyline annotation with a transform to enable "slice tracking"

### ISSUE THREAD

**Issue by jcfr** [BICCN/cell-locator#27]
I think adding the polyline under a transform and ensuring the transform is updated based on the location and orientation of the slice will enable this.

Tracking of the slide orientation and location should have a toggle. Then we can decide when and how to switch that toggle on/off when wiring all components in the interface

**Comment by jcfr** [comment]
* After annotation is placed, updating the point should be constrained to the annotation plane.

* Updating the plane normal will allow to reposition the annotation

**Comment by jcfr** [comment]
Slice should be position where the annotation is in the following scenario:
* When loading annotation
* When switching from scrolling to (placing or interacting)

**Comment by vovythevov** [comment]
Solved with PR #34
