### ISSUE TITLE
Create color table corresponding to CCF

### ISSUE THREAD

**Issue by jcfr** [BICCN/cell-locator#3]
Create color table with place holders for existing labels, and make sure it is available in the color table modules.

**Comment by dyf** [comment]
This query downloads all of the structures in the structure ontology this atlas uses:

http://api.brain-map.org/api/v2/data/Structure/query.json?criteria=[graph_id$eq1]&num_rows=2000

Each record looks like this:

{
	"acronym": "eps",
	"atlas_id": 690,
	"color_hex_triplet": "CCCCCC",
	"depth": 2,
	"failed": false,
	"failed_facet": 734881840,
	"graph_id": 1,
	"graph_order": 1218,
	"hemisphere_id": 3,
	"id": 1000,
	"name": "extrapyramidal fiber systems",
	"neuro_name_structure_id": null,
	"neuro_name_structure_id_path": null,
	"ontology_id": 1,
	"parent_structure_id": 1009,
	"safe_name": "extrapyramidal fiber systems",
	"sphinx_id": 1219,
	"st_level": 2,
	"structure_id_path": "/997/1009/1000/",
	"structure_name_facet": 738013408,
	"weight": 8690
}
The one you care about for colors is color_hex_triplet. The id field is what you'll find in the annotation volume.

**Comment by vovythevov** [comment]
After some experiments with the list of colors I got from the URL, it looks like we are going to have to implement method to allow the color table node to load categorical data (see indexed lookup: https://gitlab.kitware.com/vtk/vtk/blob/master/Common/Core/vtkScalarsToColors.h#L354-365)

**Comment by jcfr** [comment]
Would the terminology module help ?

**Comment by vovythevov** [comment]
WIP branch here: https://github.com/BICCN/cell-locator/tree/ColorMap

**Comment by jcfr** [comment]
This is now fixed in https://github.com/BICCN/cell-locator/commit/b3fa4d3953495080cf520955b67313524b0fc454

As described in https://github.com/BICCN/cell-locator/issues/4#issuecomment-419293558, Annotation dataset (annotation_50.nrrd) is automatically processed at build time to be "contiguous", a contiguous color map (a text file) based on the ontology presented in https://github.com/BICCN/cell-locator/issues/6#issuecomment-404548091 is also generated automatically and packaged.

To ensure the original `id` is displayed to the user, was also generated a json file with the mapping.

xref https://github.com/BICCN/cell-locator/issues/4#issuecomment-419293558
