### ISSUE TITLE
Option to color by layer ontology instead 

### ISSUE THREAD

**Issue by dyf** [BICCN/cell-locator#31]
I have created a script that generates a layer-oriented ontology instead of an area-oriented ontology.

https://gist.github.com/dyf/056095756b15a6b76dfb28558c4633da

Provide an option to switch between the default ontology and the layer ontology.

**Comment by jcfr** [comment]
Control for (1) the selection of coloring mode and (2) ability to show/hide color (See #43) should probably  be side by side

**Comment by jcfr** [comment]
![image](https://user-images.githubusercontent.com/219043/50290712-89eaee00-043a-11e9-9331-edd87a228f63.png)

**Comment by jcfr** [comment]
Color table for layer ontology has been fixed:

![image](https://user-images.githubusercontent.com/219043/50292866-42676080-0440-11e9-9c8f-bcd6fae9712e.png)

**Comment by jcfr** [comment]
For future reference, updated script is available at https://gist.github.com/jcfr/dedbb88054b208b534a5bda397a5b159
