### ISSUE TITLE
slicing artifacts on off-angle slices

### ISSUE THREAD

**Issue by dyf** [BICCN/cell-locator#47]
Version: 0.1.0-2018-11-05

When I slice off-axis, I see strange mislabeled bands (rectangular stripes in the attached image).  I don't see these when I slice on a cardinal axis.  Possibly strange/incorrect interpolation?

![image](https://user-images.githubusercontent.com/1854389/48723434-7c440d80-ebdb-11e8-9e66-d17cc05025f5.png)

**Comment by jcfr** [comment]
This should be fixed by https://github.com/BICCN/cell-locator/commit/9eb0e2f91ce54ee946525d510a87cd0d2ad1642f

This should be tested when a new installer is distributed, in the mean time I marked the issue as "qa:biccn"
