### ISSUE TITLE
use acronym/abbreviation instead of full name in breadcrumb

### ISSUE THREAD

**Issue by dyf** [BICCN/cell-locator#59]

**Comment by jcfr** [comment]
Structure ontology:

![image](https://user-images.githubusercontent.com/219043/50350020-aa36ad80-050b-11e9-90cf-fbbe834d9fc3.png)

Layer ontology:

![image](https://user-images.githubusercontent.com/219043/50350031-b6226f80-050b-11e9-88fc-e1c45a54bac9.png)
