### ISSUE TITLE
Color the CCF by segment

### ISSUE THREAD

**Issue by jcfr** [BICCN/cell-locator#6]
After creating the color table (See #3), there are few approaches to generate the "segments" and have them displayed in 3D:
1. Import the label map into segmentation module and generate corresponding segments
1. Use model maker to generate the model for each "non air" label listed in the color table

First, I suggest to evaluate approach 1. Depending on the time it takes, we could look into saving the generated segmentations and bundling it with the application.  If loading the segmentation file also take times, some profiling would also be needed.

**Comment by dyf** [comment]
This query downloads all of the structures in the structure ontology this atlas uses:

http://api.brain-map.org/api/v2/data/Structure/query.json?criteria=[graph_id$eq1]&num_rows=2000

Each record looks like this:

```javascript
{
	"acronym": "eps",
	"atlas_id": 690,
	"color_hex_triplet": "CCCCCC",
	"depth": 2,
	"failed": false,
	"failed_facet": 734881840,
	"graph_id": 1,
	"graph_order": 1218,
	"hemisphere_id": 3,
	"id": 1000,
	"name": "extrapyramidal fiber systems",
	"neuro_name_structure_id": null,
	"neuro_name_structure_id_path": null,
	"ontology_id": 1,
	"parent_structure_id": 1009,
	"safe_name": "extrapyramidal fiber systems",
	"sphinx_id": 1219,
	"st_level": 2,
	"structure_id_path": "/997/1009/1000/",
	"structure_name_facet": 738013408,
	"weight": 8690
}
```

The one you care about for colors is "color_hex_triplet".

**Comment by dyf** [comment]
Ah sorry, I see there is a separate issue for creating the color table -- replicating my comment there.

**Comment by jcfr** [comment]
Closing. Duplicated of https://github.com/BICCN/cell-locator/issues/10

Following last discussion, we will not generated 3d models and will not enable volume rendering
