### ISSUE TITLE
display world coordinates near breadcrumb

### ISSUE THREAD

**Issue by dyf** [BICCN/cell-locator#60]

**Comment by jcfr** [comment]
With structure ontology:

![image](https://user-images.githubusercontent.com/219043/50350860-70b37180-050e-11e9-9430-74ee82fbc2fc.png)

With layer ontology:

![image](https://user-images.githubusercontent.com/219043/50350882-81fc7e00-050e-11e9-9bf7-847d62f9a981.png)

With layer ontology but without any visible label:

![image](https://user-images.githubusercontent.com/219043/50350905-8de84000-050e-11e9-9e3d-c29afb742cb3.png)
