### ISSUE TITLE
slice extent in 2D view cropped after interations

### ISSUE THREAD

**Issue by dyf** [BICCN/cell-locator#64]
After spending some time doing the following:

1. resizing the window
2. reorienting the plane in the 3D view 
3. Twiddling pitch/yaw/roll/slice position

After this I noticed that the extent of the slice plane in the 2D view is off center.  Some sort of way to adjust this might be a good idea.  Reset button?  Panning?  I'm not sure.

![image](https://user-images.githubusercontent.com/1854389/51641470-16496e80-1f1b-11e9-865a-e699e99dd89a.png)

**Comment by jcfr** [comment]
> Reset button?

We could add a "Reset" button on the left of slice slider

**Comment by jcfr** [comment]
A reset field of view button was added:

![image](https://user-images.githubusercontent.com/219043/51719637-3f035e00-2018-11e9-892c-8b107f4c0e67.png)
