### ISSUE TITLE
A confirmation dialog is displayed after loading an annotation without modifying it.

### ISSUE THREAD

**Issue by jcfr** [BICCN/cell-locator#87]
**Description**
A confirmation dialog is displayed after loading an annotation without modifying it.

**Expected behavior**
User shouldn't be presented with a confirmation dialog 

**How to Reproduce**

1. Start the application
2. Then load an annotation
3. Close the application
4. A confirmation dialog appear

**Comment by wbwakeman** [comment]
Duplicate of #111 ?

**Comment by allemangD** [comment]
I agree; this is just a special case of #111 when the scene is empty. Closing.
