### ISSUE TITLE
Display an off-ijk-axis slice plane for the CCF

### ISSUE THREAD

**Issue by mgrauer** [BICCN/cell-locator#9]
It's possible this has other issues as dependencies, if so, please note them.

**Comment by vovythevov** [comment]
@dyf  
I'm looking at the issue #9 (https://github.com/BICCN/cell-locator/issues/9). 
I am not sure I understand what you mean by off-axis slice plane ? Is this what you want to do ?
![show3d](https://user-images.githubusercontent.com/426898/42637408-15cd3c76-85b9-11e8-871e-2f6d955f24b2.png)
You can show the slices in 3D by clicking the eye on the 2D viewer (the red star in the picture above).

**Comment by jcfr** [comment]
Hi Johan,

Off axis means "reformat"

Jc

**Comment by vovythevov** [comment]
@jcfr: Thanks !

@dyf: We can make any view off-axis if we want to. You can do it right now by clicking the reformat button on a slice view:
![reformat](https://user-images.githubusercontent.com/426898/42638455-ac7c46ce-85bb-11e8-9209-333f2a8c2e75.png)

By default three axis views are displayed: Axial, Sagittal and Coronal. We can change the layout of the application (default is "Four-Up") to move the 2D slice windows position with respect to the 3D view window. 

I think our option to display the off-axis view are:
-  Do nothing and let the user decide if they want to change one of the views to off-axis.
-  Taking over one of the default axis view and make it reformat by default.
-  Adding a slice view dedicated to the off-axis view. 
   In that case, I would suggest we use something like this ?
![proposedlayout](https://user-images.githubusercontent.com/426898/42639972-416b8a94-85bf-11e8-8482-ebeaf0e50c87.png)
What do you think ? 


For reference here are all the layouts available:
![layouts](https://user-images.githubusercontent.com/426898/42638529-d9996718-85bb-11e8-97ca-e1865d383c1f.png)

**Comment by dyf** [comment]
@vovythevov Thanks for the explanation.  I like your suggestion of adding a dedicated panel for the non cardinal/off-axis slice.
