### ISSUE TITLE
Launch CellLocator with file, angle and plane

### ISSUE THREAD

**Issue by wbwakeman** [BICCN/cell-locator#97]
**What's the problem this feature will solve?**
When an automated system launches Cell Locator for the user, Cell Locator will automatically be started in the correct orientation for pinning a selected cell.

**Describe the solution you'd like**
Can launch cell locator from the Windows command line with three arguments:
a valid Cell Locator JSON file
an angle (in degrees)
a plane of section ('coronal' or 'sagittal')

Example:
"C:\Program Files\CellLocator 0.1.0-2019-06-03\CellLocator.exe" existing_file.json 107 coronal

**Alternative Solutions**
It is possible to set this manually in the current version of the app.  This is a convenience (and error-prevention) function for frequent users of the tool.

Help us understand how to convert a plane and angle into coordinate values that Cell Locator already uses, so that we can just put those values directly into a JSON file that is used to launch Cell Locator.  Therefore, no additional (new) arguments are needed.

**Additional context**

**Comment by jcfr** [comment]
I suggest we name each parameters. What about the following:

```
"C:\Program Files\CellLocator 0.1.0-2019-06-03\CellLocator.exe" --annotation existing_file.json --angle 107 --reference-view coronal
```
Also, since both the reference view and the angle are already saved in the json file. Could you clarify the behavior if the command line parameter conflict if what is saved in the json file ?

For reference, the angle is indirectly saved as direction cosines. Here is an example of annotation file:

```json
{
    "DefaultCameraPosition": [
        5898.409902798239,
        -55040.09436164174,
        -4029.1553524665607
    ],
    "DefaultCameraViewUp": [
        0.0,
        0.0,
        1.0
    ],
    "DefaultOntology": "Structure",
    "DefaultReferenceView": "Coronal",
    "DefaultRepresentationType": "spline",
    "DefaultSplineOrientation": [
        -0.7352266424938825,
        -0.20695588865614365,
        -0.6454541380436916,
        5686.499999999999,
        0.5733606946295328,
        0.31800464826146299,
        -0.7550699024183482,
        -6599.999999999999,
        -0.361523578789984,
        0.9252255421434573,
        0.11514511776116449,
        -3987.4999999999997,
        0.0,
        0.0,
        0.0,
        1.0
    ],
    "DefaultStepSize": 24.999999999999998,
    "DefaultThickness": 50.0,
    "Locked": 0,
    "MarkupLabelFormat": "%N-%d",
    "Markups": [
        {
            "AssociatedNodeID": "vtkMRMLModelNode5",
            "CameraPosition": [
                5898.409902798239,
                -55040.09436164174,
                -4029.1553524665607
            ],
            "CameraViewUp": [
                0.0,
                0.0,
                1.0
            ],
            "Closed": 1,
            "Description": "",
            "ID": "vtkMRMLMarkupsSplinesNode_0",
            "Label": "Annotation-1",
            "Locked": 1,
            "Ontology": "Structure",
            "OrientationWXYZ": [
                0.0,
                0.0,
                0.0,
                1.0
            ],
            "Points": [
                {
                    "x": 4287.438446022345,
                    "y": -5215.645367869694,
                    "z": -2752.0637924713034
                },
                {
                    "x": 3379.037823655699,
                    "y": -4514.478472760518,
                    "z": -3246.2308292099417
                },
                {
                    "x": 2952.6701103382495,
                    "y": -4373.89624322702,
                    "z": -4714.39029476376
                },
                {
                    "x": 3279.06374172339,
                    "y": -4823.970087958516,
                    "z": -5836.149484603918
                },
                {
                    "x": 4289.332831151587,
                    "y": -5488.703727000097,
                    "z": -4532.038609011159
                },
                {
                    "x": 4369.919900137854,
                    "y": -5406.70569656342,
                    "z": -3542.595858805885
                }
            ],
            "Points_Count": "6",
            "ReferenceView": "Coronal",
            "RepresentationType": "spline",
            "Selected": 1,
            "SplineOrientation": [
                -0.7352266424938825,
                -0.20695588865614365,
                -0.6454541380436916,
                5686.499999999999,
                0.5733606946295328,
                0.31800464826146299,
                -0.7550699024183482,
                -6599.999999999999,
                -0.361523578789984,
                0.9252255421434573,
                0.11514511776116449,
                -3987.4999999999997,
                0.0,
                0.0,
                0.0,
                1.0
            ],
            "StepSize": 24.999999999999998,
            "Thickness": 50.0,
            "Visibility": 1
        }
    ],
    "Markups_Count": 1,
    "TextList": [
        null
    ],
    "TextList_Count": 0
} 
```

**Comment by wbwakeman** [comment]
>>if the command line parameter conflict if what is saved in the json file
command line parameters are optional, but if they do exist then they would take precedence over what is in the file

**Comment by jcfr** [comment]
>  they would take precedence over what is in the file

Sounds good.

Would it be possible to clarify what is the angle ? Should it be roll,  pitch or yaw ?

**Comment by wbwakeman** [comment]
>>Would it be possible to clarify what is the angle ? Should it be roll, pitch or yaw ?

I'll have to ask the experts to be certain on that one

**Comment by wbwakeman** [comment]
Hi @jcfr I have gotten some more information on how they make the cuts, and how they describe them.  I am not feeling confident in my ability to translate those into the pitch/yaw/roll coordinate system that Cell Locator uses, so I have prepared visual aids that I hope will describe the system that our laboratories are providing. Have a look at these and let me know if that is helpful, or if you need more description.

<img width="636" alt="20200325_coronal_cuts" src="https://user-images.githubusercontent.com/1855315/77556708-140fd680-6e76-11ea-8447-64a179d29be9.png">

<img width="537" alt="20200325_sagittal_cuts" src="https://user-images.githubusercontent.com/1855315/77556736-1c681180-6e76-11ea-962f-60ba9f7af873.png">

**Comment by jcfr** [comment]
> command line parameters are optional, but if they do exist then they would take precedence over what is in the file

In the current implementation, if there is an annotation in the json file, it will be loaded and the reference view and and angles specified in the command line will be ignored.

We could revisit this when multiple annotation will be supported.

**Comment by jcfr** [comment]
@wbwakeman  The installer available here is adding support for the following argument: 

```
  --reference-view                              Axial, Coronal or Sagittal
  --view-angle                                  Angle in degree
  --annotation-file                             Path to an existing annotation file
```

See https://github.com/BICCN/cell-locator/releases/tag/0.1.0-2020-04-30
