### ISSUE TITLE
Integration of annotated MNI space for human brain.

### ISSUE THREAD

**Issue by jcfr** [BICCN/cell-locator#99]
**What's the problem this feature will solve?**

In the context of the `Patch-seq` workflow, the Human neuroanatomy team at Allen may perform pinning for human specimen.

We are using ICBM 152 symmetric template 2009b:
* Download link: http://www.bic.mni.mcgill.ca/~vfonov/icbm/2009/mni_icbm152_nlin_sym_09b_nifti.zip
* Source Information about this template is here:   http://www.bic.mni.mcgill.ca/ServicesAtlases/ICBM152NLin2009

**Describe the solution you'd like**

**Alternative Solutions**

**Additional context**

* Import MNI space to Cell Locator (ICBM-152 symmetric template)
* Import Allen Institute 3D annotations using the BrainSpan Human ontology.

**Comment by jcfr** [comment]
@wbwakeman  

Would it be possible to provide the  3D annotations along with the ontology ? 

Which data should be loaded in the application: pd, t1 or t2 ?

**Comment by wbwakeman** [comment]
@jcfr Thanks for opening this issue to track the work.  I will see if I can track down someone that may have answers to your questions.

**Comment by jcfr** [comment]
> Would it be possible to provide the 3D annotations along with the ontology ?

See https://community.brain-map.org/t/allen-human-reference-atlas-3d-2020-new/405

See also TERMS OF USE for proper acknowledgment

**Comment by wbwakeman** [comment]
Please use the T1:
mni_icbm152_t1_tal_nlin_sym_09b_hires.nii

Yes, it is possible to use the Allen Human reference described in the forum link.

**Comment by jcfr** [comment]
Since the MNI and the CCF dataset are associated with different workflow, I am thinking about:
* adding a command line argument called `--atlas-type` that could take the value `CCF` or `MNI`
* saving the atlas type in the annotation file
* adding a combox in the application allowing to switch between the two dataset

Does that make sense ?

**Comment by wbwakeman** [comment]
Makes sense to me

**Comment by jcfr** [comment]
For reference, some screenshot illustrating the MNI loaded in Slicer (note that the color mapping is not the correct one)

* with annotation loaded as binary label map:

![image](https://user-images.githubusercontent.com/219043/84833016-591e5180-affc-11ea-8fd5-bac5ce2f6ee0.png)

* with annotation converted to independent segments and rendered as surface in 3D:

![image](https://user-images.githubusercontent.com/219043/84833293-01341a80-affd-11ea-9549-0cef0f961d60.png)

**Comment by jcfr** [comment]
Details to gather the correct ontology information are available in this script: http://download.alleninstitute.org/informatics-archive/allen_human_reference_atlas_3d_2020/version_1/examples/convert_to_itksnap/convert_to_itksnap.py
